# This file is machine-generated - editing it directly is not advised

[[GroupSlices]]
git-tree-sha1 = "4de31f97ac545bf533eef17109725dfc68e29d64"
uuid = "d853e229-7c7c-56e9-b6be-9a1acc5f13d9"
version = "0.0.3"
